// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace prjMusicBetter.Models;

public partial class dbSoundBetterContext : DbContext
{
    public dbSoundBetterContext()
    {
    }

    public dbSoundBetterContext(DbContextOptions<dbSoundBetterContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TMember> TMembers { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=192.168.22.199;Initial Catalog=dbSoundBetter;User ID=bbb;Password=123");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TMember>(entity =>
        {
            entity.HasKey(e => e.FMemberId);

            entity.ToTable("tMember");

            entity.Property(e => e.FMemberId).HasColumnName("fMemberID");
            entity.Property(e => e.FBirthday)
                .HasColumnType("datetime")
                .HasColumnName("fBirthday");
            entity.Property(e => e.FCreationTime)
                .HasColumnType("datetime")
                .HasColumnName("fCreationTime");
            entity.Property(e => e.FEmail)
                .HasMaxLength(50)
                .HasColumnName("fEmail");
            entity.Property(e => e.FGender).HasColumnName("fGender");
            entity.Property(e => e.FIntroduction)
                .HasMaxLength(50)
                .HasColumnName("fIntroduction");
            entity.Property(e => e.FName)
                .HasMaxLength(50)
                .HasColumnName("fName");
            entity.Property(e => e.FPasswod)
                .HasMaxLength(50)
                .HasColumnName("fPasswod");
            entity.Property(e => e.FPermissionId).HasColumnName("fPermissionID");
            entity.Property(e => e.FPhone)
                .HasMaxLength(50)
                .HasColumnName("fPhone");
            entity.Property(e => e.FPhotoPath)
                .HasMaxLength(250)
                .HasColumnName("fPhotoPath");
            entity.Property(e => e.FUserame)
                .HasMaxLength(50)
                .HasColumnName("fUserame");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}