// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjMusicBetter.Models;

public partial class TArticlePicture
{
    public int FArticlePictureId { get; set; }

    public int FArticleId { get; set; }

    public string FPicturePath { get; set; }

    public virtual TArticle FArticle { get; set; }
}