// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjMusicBetter.Models;

public partial class TArticleClick
{
    public int FArticleClickId { get; set; }

    public int? FArticleId { get; set; }

    public int? FArticleClick { get; set; }

    public virtual TArticle FArticle { get; set; }
}