// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjMusicBetter.Models;

public partial class TChatMessage
{
    public int FChatId { get; set; }

    public int? FSendMemberId { get; set; }

    public int? FReceiveMemberId { get; set; }

    public string FContent { get; set; }

    public DateTime? FTime { get; set; }
}