// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjMusicBetter.Models;

public partial class TDealClass
{
    public int FDealClassId { get; set; }

    public int FMemberId { get; set; }

    public DateTime? FDealdate { get; set; }

    public decimal? FPrice { get; set; }

    public virtual TMember FMember { get; set; }

    public virtual ICollection<TDealClassDetail> TDealClassDetails { get; set; } = new List<TDealClassDetail>();
}