// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjMusicBetter.Models;

public partial class TDealProject
{
    public int FDealProject { get; set; }

    public int FProjectId { get; set; }

    public int FMemberId { get; set; }

    public DateTime? FStartdate { get; set; }

    public DateTime? FEnddate { get; set; }

    public decimal? FPrice { get; set; }

    public int? FCouponId { get; set; }

    public virtual TCoupon FCoupon { get; set; }

    public virtual TMember FMember { get; set; }

    public virtual TProject FProject { get; set; }
}