// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjMusicBetter.Models;

public partial class TDealClassDetail
{
    public int FDealClassDetailId { get; set; }

    public int? FDealClassId { get; set; }

    public int? FMemberId { get; set; }

    public int? FClassId { get; set; }

    public virtual TClass FClass { get; set; }

    public virtual TDealClass FDealClass { get; set; }
}