// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjMusicBetter.Models;

public partial class TDealSiteLoan
{
    public int FDealSiteLoanId { get; set; }

    public int FSiteId { get; set; }

    public int FMemberId { get; set; }

    public DateTime? FStartdate { get; set; }

    public DateTime? FEnddate { get; set; }

    public decimal? FPrice { get; set; }

    public int? FCoupon { get; set; }

    public virtual TCoupon FCouponNavigation { get; set; }

    public virtual TMember FMember { get; set; }

    public virtual TSite FSite { get; set; }
}