// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjMusicBetter.Models;

public partial class TEvaluateStatus
{
    public int FEvaluateStatusId { get; set; }

    public string FDescriptiion { get; set; }

    public virtual ICollection<TEvaluate> TEvaluates { get; set; } = new List<TEvaluate>();
}