// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace prjMusicBetter.Models;

public partial class TMember
{
    public int FMemberId { get; set; }

    [Display(Name = "使用者名稱")]
    public string FUserame { get; set; }
    [Display(Name = "姓名")]
    public string FName { get; set; }
    [Display(Name = "密碼")]
    public string FPassword { get; set; }
    [Display(Name = "密碼")]
    public string FPhone { get; set; }
    [Display(Name = "電子信箱")]
    public string FEmail { get; set; }
    public int? FGender { get; set; }
    [Display(Name = "生日")]
    public DateTime? FBirthday { get; set; }
    [Display(Name = "建立時間")]
    public DateTime? FCreationTime { get; set; }
    [Display(Name = "自我介紹")]
    public string FIntroduction { get; set; }
   
    public int? FPermissionId { get; set; }
    [Display(Name = "照片")]
    public string FPhotoPath { get; set; }

    public virtual TMemberPromission FPermission { get; set; }

    public virtual ICollection<TApplicationRecord> TApplicationRecords { get; set; } = new List<TApplicationRecord>();

    public virtual ICollection<TArticleFav> TArticleFavs { get; set; } = new List<TArticleFav>();

    public virtual ICollection<TArticle> TArticles { get; set; } = new List<TArticle>();

    public virtual ICollection<TClassFav> TClassFavs { get; set; } = new List<TClassFav>();

    public virtual ICollection<TClass> TClasses { get; set; } = new List<TClass>();

    public virtual ICollection<TDealClass> TDealClasses { get; set; } = new List<TDealClass>();

    public virtual ICollection<TDealProject> TDealProjects { get; set; } = new List<TDealProject>();

    public virtual ICollection<TDealSiteLoan> TDealSiteLoans { get; set; } = new List<TDealSiteLoan>();

    public virtual ICollection<TEvaluate> TEvaluates { get; set; } = new List<TEvaluate>();

    public virtual ICollection<TMemberCoupon> TMemberCoupons { get; set; } = new List<TMemberCoupon>();

    public virtual ICollection<TMemberRelation> TMemberRelations { get; set; } = new List<TMemberRelation>();

    public virtual ICollection<TMemberSite> TMemberSites { get; set; } = new List<TMemberSite>();

    public virtual ICollection<TMemberSkill> TMemberSkills { get; set; } = new List<TMemberSkill>();

    public virtual ICollection<TNotification> TNotifications { get; set; } = new List<TNotification>();

    public virtual ICollection<TProjectFav> TProjectFavs { get; set; } = new List<TProjectFav>();

    public virtual ICollection<TProject> TProjects { get; set; } = new List<TProject>();

    public virtual ICollection<TSite> TSites { get; set; } = new List<TSite>();

    public virtual ICollection<TWorkFav> TWorkFavs { get; set; } = new List<TWorkFav>();

    public virtual ICollection<TWork> TWorks { get; set; } = new List<TWork>();
}