// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace prjMusicBetter.Models;

public partial class TMember
{
    public int FMemberId { get; set; }

    [DisplayName("使用者姓名")] // 這個就是顯示在表格標題上的文字
    public string FUserame { get; set; }
    [DisplayName("姓名")] // 這個就是顯示在表格標題上的文字
    public string FName { get; set; }
    [DisplayName("密碼")] // 這個就是顯示在表格標題上的文字
    public string FPassword { get; set; }
    [DisplayName("電話")] // 這個就是顯示在表格標題上的文字
    public string FPhone { get; set; }
    [DisplayName("電子郵箱")] // 這個就是顯示在表格標題上的文字
    public string FEmail { get; set; }
    [DisplayName("性別")] // 這個就是顯示在表格標題上的文字
    public int? FGender { get; set; }
    [DisplayName("生日")] // 這個就是顯示在表格標題上的文字
    public DateTime? FBirthday { get; set; }
    [DisplayName("創立時間")] // 這個就是顯示在表格標題上的文字
    public DateTime? FCreationTime { get; set; }
    [DisplayName("自我介紹")] // 這個就是顯示在表格標題上的文字
    public string FIntroduction { get; set; }

    public int? FPermissionId { get; set; }
    [DisplayName("我的頭像")] // 這個就是顯示在表格標題上的文字
    public string FPhotoPath { get; set; }

    public virtual TMemberPromission FPermission { get; set; }

    public virtual ICollection<TApplicationRecord> TApplicationRecords { get; set; } = new List<TApplicationRecord>();

    public virtual ICollection<TArticle> TArticles { get; set; } = new List<TArticle>();

    public virtual ICollection<TClass> TClasses { get; set; } = new List<TClass>();

    public virtual ICollection<TDealClass> TDealClasses { get; set; } = new List<TDealClass>();

    public virtual ICollection<TDealProject> TDealProjects { get; set; } = new List<TDealProject>();

    public virtual ICollection<TDealSiteLoan> TDealSiteLoans { get; set; } = new List<TDealSiteLoan>();

    public virtual ICollection<TEvaluate> TEvaluates { get; set; } = new List<TEvaluate>();

    public virtual ICollection<TMemberCoupon> TMemberCoupons { get; set; } = new List<TMemberCoupon>();

    public virtual ICollection<TMemberRelation> TMemberRelations { get; set; } = new List<TMemberRelation>();

    public virtual ICollection<TMemberSite> TMemberSites { get; set; } = new List<TMemberSite>();

    public virtual ICollection<TMemberSkill> TMemberSkills { get; set; } = new List<TMemberSkill>();

    public virtual ICollection<TProject> TProjects { get; set; } = new List<TProject>();

    public virtual ICollection<TSite> TSites { get; set; } = new List<TSite>();

    public virtual ICollection<TWork> TWorks { get; set; } = new List<TWork>();
}