// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjMusicBetter.Models;

public partial class TMemberRelationStatus
{
    public int FMemberRelationStatusId { get; set; }

    public string FDescription { get; set; }

    public virtual ICollection<TMemberRelation> TMemberRelations { get; set; } = new List<TMemberRelation>();
}