// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjMusicBetter.Models;

public partial class TMember
{
    public int FMemberId { get; set; }

    public string FUserame { get; set; }

    public string FName { get; set; }

    public string FPasswod { get; set; }

    public string FPhone { get; set; }

    public string FEmail { get; set; }

    public bool? FGender { get; set; }

    public DateTime? FBirthday { get; set; }

    public DateTime? FCreationTime { get; set; }

    public string FIntroduction { get; set; }

    public int? FPermissionId { get; set; }

    public string FPhotoPath { get; set; }
}