// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjMusicBetter.Models;

public partial class TMemberSkill
{
    public int FMemberSkillId { get; set; }

    public int FMemberId { get; set; }

    public int FSkillId { get; set; }

    public int? FYearExp { get; set; }

    public string FDescription { get; set; }

    public virtual TMember FMember { get; set; }

    public virtual TSkill FSkill { get; set; }
}