// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjMusicBetter.Models;

public partial class TMemberPromission
{
    public int FPromissionId { get; set; }

    public string FDescription { get; set; }

    public virtual ICollection<TMember> TMembers { get; set; } = new List<TMember>();
}