// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjMusicBetter.Models;

public partial class TPlaylist
{
    public int FPlaylistId { get; set; }

    public int? FMemberId { get; set; }

    public int? FWorkId { get; set; }

    public DateTime? FUpdateTime { get; set; }
}