// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjMusicBetter.Models;

public partial class TProject
{
    public int FProjectId { get; set; }

    public int FMemberId { get; set; }

    public string FName { get; set; }

    public decimal? FBudget { get; set; }

    public DateTime? FStartdate { get; set; }

    public DateTime? FEnddate { get; set; }

    public string FDescription { get; set; }

    public int FProjectStatusId { get; set; }

    public int FSiteId { get; set; }

    public string FThumbnailPath { get; set; }

    public string FDescription2 { get; set; }

    public int? FStyleId { get; set; }

    public int? FSkillId { get; set; }

    public string FDemoFilePath { get; set; }

    public virtual TMember FMember { get; set; }

    public virtual TSkill FProject { get; set; }

    public virtual TProjectStatus FProjectStatus { get; set; }

    public virtual TSite FSite { get; set; }

    public virtual TStyle FSiteNavigation { get; set; }

    public virtual ICollection<TApplicationRecord> TApplicationRecords { get; set; } = new List<TApplicationRecord>();

    public virtual ICollection<TDealProject> TDealProjects { get; set; } = new List<TDealProject>();

    public virtual ICollection<TProjectFav> TProjectFavs { get; set; } = new List<TProjectFav>();

    public virtual ICollection<TProjectSkillRequire> TProjectSkillRequires { get; set; } = new List<TProjectSkillRequire>();
}