// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjMusicBetter.Models;

public partial class TSitePicture
{
    public int FSitePictureId { get; set; }

    public int FSiteId { get; set; }

    public string FPicturePath { get; set; }

    public virtual TSite FSite { get; set; }
}