// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjMusicBetter.Models;

public partial class TStyle
{
    public int FStyleId { get; set; }

    public string FName { get; set; }

    public string FDescription { get; set; }

    public string FThumbnailPath { get; set; }

    public virtual ICollection<TArticle> TArticles { get; set; } = new List<TArticle>();

    public virtual ICollection<TProject> TProjects { get; set; } = new List<TProject>();

    public virtual ICollection<TWork> TWorks { get; set; } = new List<TWork>();
}