// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjMusicBetter.Models;

public partial class TWorkClick
{
    public int FWorkClick { get; set; }

    public int? FWorkId { get; set; }

    public int? FClick { get; set; }
}